VERZIJA=CDX
MODUL=ADMIN

SRCDOSROOT=$(BASEDOS)\\fmk\\admin\\1g\\

EOBJCOPY:=echo nemam sta kopirati !
PRGS=e.prg
EXE_PRGS=e.prg
CS=
ASMS=

FMK_LIBS=fmk_roba.lib fmk_svi.lib fmk_pi.lib fmk_rab.lib fmk_evn.lib fmk_sec.lib fmk_lok.lib xmllib.lib fmk_rule.lib fmk_exp.lib fmk_trm.lib

SCLIB_LIBS=sc1g_arh.lib sc1g_ba.lib sc1g_cui.lib sc1g_db.lib sc1g_os.lib sc1g_ost.lib sc1g_par.lib sc1g_pr.lib sc1g_sif.lib sc1g_sql.lib sc1g_ut.lib sc2g_app.lib sc2g_db.lib sc1g_rpt.lib sc2g_cui.lib sc1g_key.lib ka_s1pf.lib sc_epl2.lib sc_gvp.lib

MODUL_LIBS=ad_db.lib ad_ma.lib ad_par.lib ad_si.lib ad_ut.lib ad_imp.lib

include ../../fmk_lib/Makefile_clipper

LIBEXE:=@echo pokrenite make exe !
CPLIB:=@echo pokrenuti make exe !
RMLIB:=@echo pokrenuti make exe !

lib: exe
